### ISSUE TITLE
AdvancedSearchPlugin: updating a product results in a lot of 'update' tasks being created

### ISSUE THREAD

**Issue by nicoes** [vendure-ecommerce/vendure-plus-issues#25]
At the moment we are using the advanced search plugin. We have bufferUpdates set to 'false' so that the search index gets updated when a product (variant) changes. I noticed that a product change triggers around 140 "update" jobs with empty "variantIds". When I enable bufferUpdates and manually run the pending jobs then only one update job is triggered with the corresponding variantId (see screenshot).

Our context:
- We are running on Google Cloud Run
- We use the Google Tasks plugin.
- We have about 80 collections

<img width="1426" alt="Screenshot 2023-07-21 at 09 28 43" src="https://github.com/vendure-ecommerce/vendure-plus-issues/assets/642209/376168a4-dfd0-475b-a13c-71648df68c02">

**Comment by nicoes** [comment]
Did some debugging. Google Cloud Tasks allows you to pause a queue. This taught me the following:
- When I edit a product title: a product event is dispatched and put on the advanced-search-index queue.
- When I resume the Google Cloud Tasks queue and the product even is processed then a multitude of "CollectionModificationEvent" (about 80, looks related to the number of our collections) are received by the advanced search plugin with an "undefined" event type and empty event.productVariantIds.

<img width="445" alt="Screenshot 2023-07-24 at 15 27 26" src="https://github.com/vendure-ecommerce/vendure-plus-issues/assets/642209/35d6f8d6-e6e3-4d02-a8e4-24af05e03468">

**Comment by michaelbromley** [comment]
What I think is happening:

Whenever a product or variant is changed, we need to re-evaluate all the collection filters. This is because we don't have a way of knowing whether the change made has affected the contents of any of the collections.

You can see the code that does this here: https://github.com/vendure-ecommerce/vendure/blob/58788801ddd3152d657b3ee9c8c1471a10d6ce7c/packages/core/src/service/services/collection.service.ts#L95-L108

> with an "undefined" event type

I'm not sure what you mean by this part. Can you show an example?

> and empty event.productVariantIds

I think we should not be dispatching the event when there are no variants that are affected. This is a small fix for the core.

**Comment by nicoes** [comment]
Thanks for the clarification. I understand the CollectionModificationEvent better now.

> with an "undefined" event type
I meant: the CollectionModificationEvent doesn't have a type property. But now that I look loser, it's by design. I was under the impression that every event had a type. So never mind!

> I think we should not be dispatching the event when there are no variants that are affected. This is a small fix for the core.
Yeah that should prevent the seemingly unnecessary updates in this case 👍

**Comment by nicoes** [comment]
Thanks for looking into it so soon 🙏
